# Generated by Django 4.0.4 on 2022-07-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_shippingdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingdetail',
            name='contact',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
