# Generated by Django 4.0.4 on 2022-07-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_orderplaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Return Requested', 'Return Requested'), ('Returned', 'Returned'), ('Picked up', 'Picked up')], default='Pending', max_length=50),
        ),
    ]
